### ISSUE TITLE
Error when running initial example

### ISSUE THREAD

**Issue by Craques** [stpaine/FERS#15]
I have followed the installation steps on both Ubuntu 20.04 and macOS 10.15.5 when I try to run the examples I get the following error on both platforms, on macOS:
![Screenshot 2020-08-14 at 18 19 49](https://user-images.githubusercontent.com/11189445/90271019-74220c00-de5b-11ea-90a3-22861ee077fd.png)

on Ubuntu: 
![Screenshot from 2020-08-14 18-53-58](https://user-images.githubusercontent.com/11189445/90273750-c107e180-de5f-11ea-8dd5-e53908a3daf6.png)

I have tried to fix the issue but have not made any progress, any help would be appreciated

**Comment by Grabt234** [comment]
Hi
Were you ever able to fix this issue?

**Comment by stpaine** [comment]
Hello, no. The issue has got to do with the HDF5 libraries on newer versions of debian. The easiest way to get rid of these errors is to use an older version of ubuntu until this is resolved or to run the docker version. You can also run it as a VM.

**Comment by coopmtu** [comment]
I ran into this problem as well on Ubuntu 20.04. The root of the issue is that the file identifier for the HDF5 library is a 64 bit int (long int) and the code for FERS assumes int. The variable hid_f is cast to int in some of the functions causing the error.  The issue starts at rshdf5::AddChunkToFile but the fix (int -> long int) needs to be applied everywhere the hdf5 file id is returned as an int. I have a local copy of the code with the fix implemented and it runs fine.

**Comment by darrynjordan** [comment]
@coopmtu please would you make a pull request with the fix applied?

**Comment by coopmtu** [comment]
> @coopmtu please would you make a pull request with the fix applied?

Done.
